### ISSUE TITLE
Missing value while forming the SQL prepared statement

### ISSUE THREAD

**Issue by jsantos** [robinbortlik/validates_overlap#50]
I'm seeing an error that is intriguing me, doesn't seem to happen all the time.

I have my overlap conditions defined as: 

```ruby
  scope :active, (-> { where(deleted: false, available: true) })

  validates :starttime, :endtime, overlap: {
    query_options: { active: nil },
    scope: :user_id,
    exclude_edges: ["starttime", "endtime"],
    load_overlapped: true,
    message_title: 'overlap',
    message_content: 'overlaps with another stop',
  }
```

And I've been getting the following error recently:

```ruby
ActiveRecord::PreparedStatementInvalid: missing value for :user_id_value in (stops.endtime IS NULL OR stops.endtime > :starts_at_value) AND (stops.starttime IS NULL OR stops.starttime < :ends_at_value) AND stops.user_id  = :user_id_value
  from active_record/sanitization.rb:198:in `block in replace_named_bind_variables'
  from active_record/sanitization.rb:192:in `gsub'
  from active_record/sanitization.rb:192:in `replace_named_bind_variables'
  from active_record/sanitization.rb:126:in `sanitize_sql_array'
  from active_record/sanitization.rb:26:in `sanitize_sql_for_conditions'
  from active_record/relation/where_clause_factory.rb:14:in `build'
  from active_record/relation/query_methods.rb:591:in `where!'
  from active_record/relation/finder_methods.rb:370:in `construct_relation_for_exists'
  from active_record/relation/finder_methods.rb:320:in `exists?'
  from validates_overlap/overlap_validator.rb:52:in `overlapped_exists?'
  from validates_overlap/overlap_validator.rb:21:in `validate'
  ...
```

I've verified and `user_id` used on the `:scope` is never `nil` (no records like that, and validations protect against that. Also looked into the conditions on `overlap_validator` and don't see anything wrong. The save statement triggering this runs inside a transaction.

**Comment by robinbortlik** [comment]
Hi @jsantos , 

I haven't been maintaining this gem for a while. So not sure, what changed in the Rails world. But may I ask you, what version of rails are you using? 
Can you please push somewhere some example application where I can see and test the exception?

**Comment by jsantos** [comment]
I'm currently using Rails 5.2.3. I'll keep investigating this and will let you know if I can isolate the reason why this is happening. This is not happening all the time, so there might be some other factor involved.

**Comment by robinbortlik** [comment]
Ok, let me know if you find something.

**Comment by tilo** [comment]
@jsantos it's been a while.. You were right! 

And this is a real bug that still exists on Rails 8.1. Thank you for the detailed report — every clue in it turned out to matter.

**Root cause: the validator is shared and mutable — this is a thread-safety bug.**

Rails creates **one** `OverlapValidator` instance per model class, and that single instance is used for every validation of that class. But the validator stores its query state in instance variables ([`overlap_validator.rb#L9-L11`](https://github.com/tilo/validates_overlap/blob/main/lib/validates_overlap/overlap_validator.rb#L9-L11)):

```ruby
attr_accessor :sql_conditions
attr_accessor :sql_values
attr_accessor :scoped_model
```

When two records of the same class are validated concurrently — Puma threads, Sidekiq workers — they overwrite each other's state mid-build. The failing interleaving:

1. Thread A finishes building its query: conditions end with `AND stops.user_id  = :user_id_value`, and the values hash contains `:user_id_value`.
2. Thread B is scheduled and starts *its* validation. Its first build step (`generate_overlap_sql_values`) **replaces the shared values hash** with one that only contains the time-range values — no `:user_id_value` yet.
3. Thread A resumes and runs its `exists?` query with its own conditions but thread B's half-built values:

```
ActiveRecord::PreparedStatementInvalid: missing value for :user_id_value in:
"(... stops.endtime ... :starts_at_value) AND (... stops.starttime ... :ends_at_value) AND stops.user_id  = :user_id_value"
```

That is your exact exception — down to the double space in `user_id  = :user_id_value`, which comes from the string formatting in `add_attribute`. I reproduced it deterministically on Rails 8.1.3.1 / Ruby 3.4 by driving the shared validator instance through exactly this interleaving.

This also explains everything that made the bug impossible to pin down in 2019:

- **Intermittent:** on MRI, the GVL only preempts threads every ~100ms, and the vulnerable window is a few operations wide — so it takes an unlucky preemption. (An organic 2,000-validation thread stress produced zero hits; the deterministic interleaving fails every time.)
- **Unrelated to transactions, data, or Rails version** — `user_id` was never nil; the value goes missing from the *shared* values hash, not from your record.
- **The crash is only the visible tip.** There is a wider window where a validation silently runs with the *other* record's conditions or values — no exception, just a wrong validation result (a false "overlaps" error, or a missed overlap).

**Fix plan:** make the validator stateless — build the conditions/values/relation as locals passed through the call chain instead of instance state. Targeted for v1.2.0, with a concurrency regression test. Leaving this issue open until that ships.

**Comment by tilo** [comment]
This will be fixed in the upcoming 1.2.0 release

**Comment by tilo** [comment]
@jsantos version 1.2.0 is released
